
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	recycler = "500"
	#Energy per operation tick (Joules).
	plantingStation = "2000"
	#Energy per operation tick (Joules).
	cnc_stamper = "500"
	#Energy per operation tick (Joules).
	cnc_lathe = "500"
	#Energy per operation tick (Joules).
	cnc_rollingMill = "500"
	#Energy per operation tick (Joules).
	ambientGasCollector = "1000"
	#Energy per operation tick (Joules).
	" largeRotaryCondensentrator " = "500"
	#Energy per operation tick (Joules).
	" largeChemicalInfuser " = "1000"
	#Energy per operation tick (Joules).
	" largeAntiprotonicNucleosynthesizer " = "5000000"
	#Energy per operation tick (Joules).
	" largePigmentMixer " = "1000"

	#Settings for configuring Replicator Energy Usage
	[usage.replicator]
		#Energy per operation tick (Joules).
		itemReplicator = "1024000"
		#Energy per operation tick (Joules).
		fluidReplicator = "1024000"

